import { typedError } from '../runtime/errors.js';

export const VAL_CODES = {
  UNKNOWN_KIND: 'E_VAL_UNKNOWN_KIND',
  EMPTY: 'E_VAL_EMPTY',
  JSON_INVALID: 'E_VAL_JSON_INVALID',
  DUPLICATE_KEY: 'E_VAL_DUPLICATE_KEY',
  MISSING_FIELD: 'E_VAL_MISSING_FIELD',
  DUPLICATE_ID: 'E_VAL_DUPLICATE_ID',
  BROKEN_REF: 'E_VAL_BROKEN_REF',
  SCHEMA_MISMATCH: 'E_VAL_SCHEMA_MISMATCH',
  SCHEMA_MISSING: 'E_VAL_SCHEMA_MISSING',
  ASSET_MISSING: 'E_VAL_ASSET_MISSING',
  ASSET_CHECKSUM: 'E_VAL_ASSET_CHECKSUM',
  ASSET_MIME: 'E_VAL_ASSET_MIME',
  ASSET_INVALID: 'E_VAL_ASSET_INVALID',
  ASSET_PLACEHOLDER: 'E_VAL_ASSET_PLACEHOLDER',
  THEME_INVALID: 'E_VAL_THEME_INVALID',
  BUSINESS_INVALID: 'E_VAL_BUSINESS_INVALID',
  PROMPT_INVALID: 'E_VAL_PROMPT_INVALID',
  PROMPT_PLAIN: 'E_VAL_PROMPT_PLAIN',
  WORKFLOW_INVALID: 'E_VAL_WORKFLOW_INVALID',
  CONFIG_INVALID: 'E_VAL_CONFIG_INVALID'
};

export function valError(code, message, details = {}) {
  return typedError(code, message, details);
}
