export const WEB_CODES = {
  INVALID_BUNDLE: 'WEB_INVALID_BUNDLE',
  MISSING_CONFIG: 'WEB_MISSING_CONFIG',
  UNKNOWN_LAYOUT: 'WEB_UNKNOWN_LAYOUT',
  UNKNOWN_SECTION: 'WEB_UNKNOWN_SECTION',
  UNKNOWN_FORMAT: 'WEB_UNKNOWN_FORMAT',
  RENDER_FAILED: 'WEB_RENDER_FAILED',
  VALIDATION_FAILED: 'WEB_VALIDATION_FAILED',
  ASSET_MISSING: 'WEB_ASSET_MISSING',
  EXPORT_FAILED: 'WEB_EXPORT_FAILED'
};

export function webError(code, message, meta = {}) {
  return Object.assign(new Error(message), { code, ...meta });
}
