import { serializeBodyHtml } from '../renderer/index.js';
import { cssVariables, themeBootstrapScript } from '../theme/css.js';
import { generateSiteCss } from '../theme/site-css.js';
import { placeholderMap, resolvePlaceholders } from '../export/assets-utils.js';
import { siteScript } from '../export/site-script.js';
import { escapeHtml } from '../renderer/escape.js';
import { stableJson } from '../utils.js';

export function previewFiles(site) {
  const cssVars = cssVariables(site.theme);
  const siteCss = generateSiteCss(site.theme);
  const css = `${cssVars}\n\n${siteCss}`;
  const bootstrap = themeBootstrapScript(site.theme);
  const script = siteScript(site.theme);
  const map = placeholderMap(site);
  const pages = site.pages.map((p) => {
    const resolved = { ...p, sections: p.sections.map((s) => resolvePlaceholders(s, map)) };
    return { id: p.id, title: p.head.title, body: serializeBodyHtml(resolved.sections) };
  });
  const pageTabs = pages.map((p, i) =>
    `<button type="button" class="pv-tab${i === 0 ? ' is-active' : ''}" data-pv-target="${escapeHtml(p.id)}">${escapeHtml(p.id)}</button>`
  ).join('\n');
  const pagePanels = pages.map((p, i) =>
    `<section class="pv-page${i === 0 ? ' is-active' : ''}" data-pv-page="${escapeHtml(p.id)}">\n${p.body}\n</section>`
  ).join('\n\n');
  const pvCss = [
    'body{margin:0}',
    '.pv-bar{position:sticky;top:0;z-index:99;display:flex;align-items:center;gap:var(--space-md);padding:var(--space-sm) var(--space-md);background:rgb(var(--c-base-deep));border-bottom:1px solid rgb(var(--c-ink) / 0.1);font-family:var(--font-body, system-ui)}',
    '.pv-title{font-weight:700;font-size:0.85rem;letter-spacing:0.1em;text-transform:uppercase;color:rgb(var(--c-primary-light))}',
    '.pv-tab{background:none;border:1px solid rgb(var(--c-ink) / 0.2);color:rgb(var(--c-ink-muted));border-radius:var(--radius-full);padding:0.35rem 0.9rem;font-size:0.8rem;cursor:pointer}',
    '.pv-tab.is-active{background:rgb(var(--c-primary));color:rgb(var(--c-primary-dark));border-color:transparent}',
    '.pv-page{display:none}',
    '.pv-page.is-active{display:block}',
    '.pv-note{margin-left:auto;font-size:0.75rem;color:rgb(var(--c-ink-muted))}'
  ].join('\n');

  const meta = [
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `<title>${escapeHtml(site.name)} — Preview</title>`,
    '<meta name="robots" content="noindex, nofollow">'
  ].join('\n');

  const html = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    meta,
    site.theme.typography.fontsUrl ? `<link rel="preconnect" href="https://fonts.googleapis.com">` : '',
    site.theme.typography.fontsUrl ? `<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>` : '',
    site.theme.typography.fontsUrl ? `<link href="${escapeHtml(site.theme.typography.fontsUrl)}" rel="stylesheet">` : '',
    `<style>\n${css}\n${pvCss}\n</style>`,
    `<script>\n${bootstrap}\n</script>`,
    '</head>',
    '<body>',
    '<div class="pv-shell">',
    `<div class="pv-bar"><span class="pv-title">${escapeHtml(site.name)} — preview</span>\n${pageTabs}\n<span class="pv-note">generated by AgencyOS website-engine</span></div>`,
    pagePanels,
    '</div>',
    `<script>\n${script}\n(function(){var tabs=document.querySelectorAll("[data-pv-target]");var pages=document.querySelectorAll("[data-pv-page]");for(var i=0;i<tabs.length;i++){tabs[i].addEventListener("click",function(){for(var j=0;j<tabs.length;j++)tabs[j].classList.toggle("is-active",tabs[j]===this);for(var k=0;k<pages.length;k++)pages[k].classList.toggle("is-active",pages[k].getAttribute("data-pv-page")===this.getAttribute("data-pv-target"));});}})();</script>`,
    '</body>',
    '</html>',
    ''
  ].filter((s) => s !== '').join('\n');

  return {
    'index.html': html,
    'preview-data.json': stableJson({ businessId: site.businessId, name: site.name, layout: site.layout, pages: pages.map((p) => ({ id: p.id, title: p.title })) })
  };
}
