export function generateTailwindConfig(t) {
  const colorVar = (name) => `'rgb(var(--c-${name}) / <alpha-value>)'`;
  const palette = (mode) => {
    const keys = Object.keys(t.colors[mode]);
    const rows = keys.map((k) => `        ${JSON.stringify(k)}: ${colorVar(k)}`).join(',\n');
    return rows;
  };
  return `/** Generated by AgencyOS website-engine — deterministic. Do not edit. */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
${palette(t.defaultMode)}
      },
      fontFamily: {
        display: [${JSON.stringify(t.typography.display)}],
        body: [${JSON.stringify(t.typography.body)}]
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)'
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)'
      },
      boxShadow: {
        primary: 'var(--shadow-primary)',
        'primary-lg': 'var(--shadow-primary-lg)',
        elevated: 'var(--shadow-elevated)'
      },
      transitionTimingFunction: {
        base: 'var(--ease-base)',
        spring: 'var(--ease-spring)'
      },
      animation: {
        'fade-in': 'fadeIn 600ms var(--ease-base) both',
        'rise': 'rise 600ms var(--ease-base) both'
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        rise: { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } }
      }
    }
  },
  plugins: []
};
`;
}

export function generatePostcssConfig() {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
`;
}
