export const INT_CODES = {
  UNKNOWN_METRIC: 'INT_UNKNOWN_METRIC',
  INVALID_ENVELOPE: 'INT_INVALID_ENVELOPE',
  INVALID_POINT: 'INT_INVALID_POINT',
  INVALID_INCIDENT: 'INT_INVALID_INCIDENT',
  INVALID_ALERT_RULE: 'INT_INVALID_ALERT_RULE',
  INVALID_ALERT: 'INT_INVALID_ALERT',
  INVALID_INSIGHT: 'INT_INVALID_INSIGHT',
  INVALID_CONFIG: 'INT_INVALID_CONFIG',
  STORE_ERROR: 'INT_STORE_ERROR',
  PATH_INVALID: 'INT_PATH_INVALID',
  UNKNOWN_JOB: 'INT_UNKNOWN_JOB',
  UNKNOWN_REPORT: 'INT_UNKNOWN_REPORT'
};

export function intError(code, message, meta = {}) {
  const err = new Error(message);
  err.code = code;
  err.meta = meta;
  return err;
}
