import { typedError } from '../runtime/errors.js';

export const COM_CODES = {
  SCHEMA_INVALID: 'E_COM_SCHEMA_INVALID',
  UNKNOWN_TYPE: 'E_COM_UNKNOWN_TYPE',
  UNKNOWN_TOPIC: 'E_COM_UNKNOWN_TOPIC',
  NO_SUBSCRIBERS: 'E_COM_NO_SUBSCRIBERS',
  DELIVERY_TIMEOUT: 'E_COM_DELIVERY_TIMEOUT',
  CONSUMER_TIMEOUT: 'E_COM_CONSUMER_TIMEOUT',
  TTL_EXPIRED: 'E_COM_TTL_EXPIRED',
  RETRIES_EXHAUSTED: 'E_COM_RETRIES_EXHAUSTED',
  ACK_UNKNOWN: 'E_COM_ACK_UNKNOWN',
  DUPLICATE_SUBSCRIPTION: 'E_COM_DUPLICATE_SUBSCRIPTION',
  QUEUE_CLOSED: 'E_COM_QUEUE_CLOSED',
  TRANSPORT_FAILURE: 'E_COM_TRANSPORT_FAILURE',
  HEARTBEAT_STALE: 'E_COM_HEARTBEAT_STALE',
  NOT_ACKED: 'E_COM_NOT_ACKED',
  STATE_ILLEGAL: 'E_COM_STATE_ILLEGAL'
};

export function comError(code, message, meta = {}) {
  return typedError(code, message, meta);
}
