/** Generated by AgencyOS website-engine — deterministic. Do not edit. */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "base": 'rgb(var(--c-base) / <alpha-value>)',
        "base-deep": 'rgb(var(--c-base-deep) / <alpha-value>)',
        "surface": 'rgb(var(--c-surface) / <alpha-value>)',
        "surface-2": 'rgb(var(--c-surface-2) / <alpha-value>)',
        "surface-3": 'rgb(var(--c-surface-3) / <alpha-value>)',
        "primary": 'rgb(var(--c-primary) / <alpha-value>)',
        "primary-light": 'rgb(var(--c-primary-light) / <alpha-value>)',
        "primary-dark": 'rgb(var(--c-primary-dark) / <alpha-value>)',
        "ink": 'rgb(var(--c-ink) / <alpha-value>)',
        "ink-muted": 'rgb(var(--c-ink-muted) / <alpha-value>)'
      },
      fontFamily: {
        display: ["'Sora', sans-serif"],
        body: ["'Inter', sans-serif"]
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)'
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)'
      },
      boxShadow: {
        primary: 'var(--shadow-primary)',
        'primary-lg': 'var(--shadow-primary-lg)',
        elevated: 'var(--shadow-elevated)'
      },
      transitionTimingFunction: {
        base: 'var(--ease-base)',
        spring: 'var(--ease-spring)'
      },
      animation: {
        'fade-in': 'fadeIn 600ms var(--ease-base) both',
        'rise': 'rise 600ms var(--ease-base) both'
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        rise: { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } }
      }
    }
  },
  plugins: []
};
