export const DEL_CODES = {
  INVALID_TRACE: 'E_DEL_INVALID_TRACE',
  UNKNOWN_BUILD: 'E_DEL_UNKNOWN_BUILD',
  UNKNOWN_RECORD: 'E_DEL_UNKNOWN_RECORD',
  QA_FAILED: 'E_DEL_QA_FAILED',
  PACKAGE_MISSING: 'E_DEL_PACKAGE_MISSING',
  SCHEMA_INVALID: 'E_DEL_SCHEMA_INVALID',
  SECRET_MISSING: 'E_DEL_SECRET_MISSING',
  SECRET_SCAN_FAILED: 'E_DEL_SECRET_SCAN_FAILED',
  PROVIDER_UNKNOWN: 'E_DEL_PROVIDER_UNKNOWN',
  PROVIDER_ERROR: 'E_DEL_PROVIDER_ERROR',
  AUTH_FAILED: 'E_DEL_AUTH_FAILED',
  RATE_LIMITED: 'E_TR_RATE_LIMITED',
  NETWORK_ERROR: 'E_TR_NETWORK',
  TIMEOUT: 'E_TR_TIMEOUT',
  APPROVAL_REQUIRED: 'E_DEL_APPROVAL_REQUIRED',
  APPROVAL_NOT_PENDING: 'E_DEL_APPROVAL_NOT_PENDING',
  AUTO_DISABLED: 'E_DEL_AUTO_DISABLED',
  BAD_MODE: 'E_DEL_BAD_MODE',
  BAD_STATE: 'E_DEL_BAD_STATE',
  CONFIG_INVALID: 'E_DEL_CONFIG_INVALID',
  ROLLBACK_INVALID: 'E_DEL_ROLLBACK_INVALID',
  RETENTION_FAILED: 'E_DEL_RETENTION_FAILED',
  RECORD_CONFLICT: 'E_DEL_RECORD_CONFLICT',
  PROVIDER_BUDGET: 'E_DEL_PROVIDER_BUDGET'
};

const DEFAULT_RETRYABLE = new Set(['E_TR_RATE_LIMITED', 'E_TR_NETWORK', 'E_TR_TIMEOUT', 'E_TR_UNKNOWN']);

export function deliveryError(code, message, meta = {}) {
  const err = new Error(message);
  err.name = 'DeliveryError';
  err.code = code;
  err.meta = meta;
  if (meta.retryable !== undefined) err.retryable = meta.retryable;
  else err.retryable = DEFAULT_RETRYABLE.has(code);
  if (meta.status !== undefined) err.status = meta.status;
  return err;
}
