// src/core/icons.js
// ---------------------------------------------------------------------------
// Icon registry: maps the string icon names used inside config JSON files
// to Lucide React components. AI agents only need to write icon names like
// "map-pin" or "utensils-crossed" — never imports.
//
// Unknown names safely resolve to null (components must guard).
// ---------------------------------------------------------------------------

import {
  MapPin,
  Clock,
  Star,
  Rocket,
  UtensilsCrossed,
  CalendarCheck,
  Search,
  Phone,
  Mail,
  Navigation,
  Menu as MenuIcon,
  X,
  ShoppingBag,
  Facebook,
  Instagram,
  MessageCircle,
  CheckCircle2,
  ChevronRight,
  Sun,
  Moon,
  Users,
  Sparkles,
  Heart,
  Award,
  Dumbbell,
  Scissors,
  Stethoscope,
  Building2,
  Cake,
  Cookie,
  Pizza,
  Coffee,
  Wine,
  Salad,
  Flame,
  Truck,
  Headphones,
  PartyPopper,
  ChefHat,
  Quote,
  Plus,
  Minus,
  Send,
  Eye,
  CalendarDays,
  Star as StarIcon,
} from 'lucide-react'

const registry = {
  'map-pin': MapPin,
  'clock': Clock,
  'star': Star,
  'rocket': Rocket,
  'utensils-crossed': UtensilsCrossed,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  'search': Search,
  'phone': Phone,
  'mail': Mail,
  'navigation': Navigation,
  'menu': MenuIcon,
  'x': X,
  'shopping-bag': ShoppingBag,
  'facebook': Facebook,
  'instagram': Instagram,
  'whatsapp': MessageCircle,
  'message-circle': MessageCircle,
  'check-circle': CheckCircle2,
  'chevron-right': ChevronRight,
  'sun': Sun,
  'moon': Moon,
  'users': Users,
  'sparkles': Sparkles,
  'heart': Heart,
  'award': Award,
  'dumbbell': Dumbbell,
  'scissors': Scissors,
  'stethoscope': Stethoscope,
  'building-2': Building2,
  'building': Building2,
  'cake': Cake,
  'cookie': Cookie,
  'pizza': Pizza,
  'coffee': Coffee,
  'wine': Wine,
  'salad': Salad,
  'flame': Flame,
  'truck': Truck,
  'headphones': Headphones,
  'party-popper': PartyPopper,
  'chef-hat': ChefHat,
  'quote': Quote,
  'plus': Plus,
  'minus': Minus,
  'send': Send,
  'eye': Eye,
}

export function icon(name) {
  if (!name) return null
  return registry[String(name).toLowerCase().replace(/\s+/g, '-')] || null
}
