export const PIP_CODES = {
  INVALID_INPUT: 'PIP_INVALID_INPUT',
  INVALID_DOSSIER: 'PIP_INVALID_DOSSIER',
  UNKNOWN_PIPELINE: 'PIP_UNKNOWN_PIPELINE',
  UNKNOWN_STAGE: 'PIP_UNKNOWN_STAGE',
  STAGE_FAILED: 'PIP_STAGE_FAILED',
  RESUME_FAILED: 'PIP_RESUME_FAILED',
  GENERATION_FAILED: 'PIP_GENERATION_FAILED',
  VALIDATION_FAILED: 'PIP_VALIDATION_FAILED',
  QA_FAILED: 'PIP_QA_FAILED',
  STORE_ERROR: 'PIP_STORE_ERROR',
  VERSION_MISMATCH: 'PIP_VERSION_MISMATCH',
  DEPENDENCY_CYCLE: 'PIP_DEPENDENCY_CYCLE'
};

export function pipError(code, message, meta = {}) {
  const err = new Error(message);
  err.code = code;
  err.meta = meta;
  return err;
}
