export function typedError(code, message, props = {}) {
  const err = new Error(message);
  err.code = code;
  err.meta = { ...(err.meta || {}), ...props };
  return err;
}

export const CODES = {
  TRANSIENT_TIMEOUT: 'E_TR_TIMEOUT',
  TRANSIENT_NETWORK: 'E_TR_NETWORK',
  TRANSIENT_RATE_LIMIT: 'E_TR_RATE_LIMITED',
  TRANSIENT_UNKNOWN: 'E_TR_UNKNOWN',
  VALIDATION_SCHEMA: 'E_VA_SCHEMA',
  VALIDATION_MISSING: 'E_VA_MISSING_KEY',
  DATA_NO_EVIDENCE: 'E_DA_NO_EVIDENCE',
  DATA_CONFLICT: 'E_DA_UNRESOLVED_CONFLICT',
  DATA_SIMULATION: 'E_DA_SIMULATION',
  INFRA_STORAGE: 'E_IN_STORAGE',
  INFRA_AUTH: 'E_IN_AUTH',
  INFRA_UNKNOWN: 'E_IN_UNKNOWN',
  STATE_UNKNOWN_AGENT: 'E_ST_UNKNOWN_AGENT',
  STATE_UNKNOWN_WORKFLOW: 'E_ST_UNKNOWN_WORKFLOW',
  STATE_UNKNOWN_ACTOR: 'E_ST_UNKNOWN_ACTOR',
  STATE_INVALID_TRANSITION: 'E_ST_INVALID_TRANSITION',
  STATE_CYCLIC: 'E_ST_CYCLIC',
  STATE_CONTEXT: 'E_ST_CONTEXT'
};
