export const CATALOG = [
  {
    name: 'Koshary El Tahrir',
    category: 'restaurant',
    area: 'Cairo',
    country: 'EG',
    address: '12 Tahrir Square, Downtown, Cairo',
    phone: '+20 10 0123 4567',
    whatsapp: '+201001234567',
    rating: 4.3,
    reviews: 1240,
    instagram: 'https://instagram.com/kosharyeltahrir',
    facebook: 'https://facebook.com/kosharyeltahrir',
    email: 'info@kosharyeltahrir.com',
    openingHours: ['Sat-Thu 08:00-23:00'],
    photos: ['photo-1.jpg', 'photo-2.jpg'],
    sources: ['google-maps', 'facebook']
  },
  {
    name: 'Cairo Roastery',
    category: 'cafe',
    area: 'Cairo',
    country: 'EG',
    address: '45 Zamalek, 26th July St, Cairo',
    phone: '022 735 7788',
    whatsapp: '+20 122 555 7788',
    rating: 4.6,
    reviews: 830,
    website: 'http://www.cairoroastery.com',
    instagram: 'https://instagram.com/cairoroastery',
    openingHours: ['Daily 07:00-00:00'],
    photos: ['roast-1.jpg', 'roast-2.jpg', 'roast-3.jpg', 'roast-4.jpg'],
    sources: ['google-maps', 'instagram'],
    simulatedProbe: { ok: true, status: 200, timeMs: 4200, isHttps: false, html: '<html><head><title>Cairo Roastery</title></head><body><h1>Cairo Roastery</h1></body></html>' }
  },
  {
    name: 'Bella Pizza',
    category: 'pizza',
    area: 'Cairo',
    country: 'EG',
    address: '8 Mohandessin, Dokki, Cairo',
    phone: '+20 106 000 1122',
    whatsapp: '+20 106 000 1122',
    rating: 4.1,
    reviews: 560,
    website: 'https://www.bellapizza-eg.com',
    facebook: 'https://facebook.com/bellapizzaeg',
    openingHours: ['Daily 11:00-02:00'],
    photos: ['pizza-1.jpg', 'pizza-2.jpg', 'pizza-3.jpg', 'pizza-4.jpg', 'pizza-5.jpg'],
    sources: ['google-maps'],
    simulatedProbe: { ok: false, status: 500, timeMs: 900, error: 'HTTP 500 Internal Server Error', isHttps: true, html: '' }
  },
  {
    name: 'Aswan Bakery',
    category: 'bakery',
    area: 'Aswan',
    country: 'EG',
    address: '23 Corniche El Nil, Aswan',
    phone: '097 231 4455',
    rating: 3.8,
    reviews: 210,
    facebook: 'https://facebook.com/aswanbakery',
    openingHours: ['Daily 06:00-21:00'],
    photos: ['bread-1.jpg', 'bread-2.jpg', 'bread-3.jpg', 'bread-4.jpg', 'bread-5.jpg'],
    sources: ['directory']
  },
  {
    name: 'Nile Dental Clinic',
    category: 'clinic',
    area: 'Cairo',
    country: 'EG',
    address: '9 Garden City, Cairo',
    phone: '+20 2 2795 1122',
    whatsapp: '+20 100 555 8899',
    rating: 4.8,
    reviews: 95,
    website: 'https://www.niledentalclinic.com',
    email: 'care@niledentalclinic.com',
    openingHours: ['Sat-Thu 10:00-20:00'],
    photos: ['clinic-1.jpg', 'clinic-2.jpg', 'clinic-3.jpg', 'clinic-4.jpg', 'clinic-5.jpg', 'clinic-6.jpg', 'clinic-7.jpg', 'clinic-8.jpg'],
    sources: ['google-maps', 'website'],
    simulatedProbe: { ok: true, status: 200, timeMs: 480, isHttps: true, html: '<html lang="en"><head><title>Nile Dental Clinic | Dentistry in Cairo</title><meta name="description" content="Modern dentistry in Garden City."><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><h1>Nile Dental Clinic</h1><p>&copy; 2025 Nile Dental Clinic</p></body></html>' }
  },
  {
    name: 'Zamalek Power Gym',
    category: 'gym',
    area: 'Cairo',
    country: 'EG',
    address: '31 Gabalaya St, Zamalek, Cairo',
    phone: '010 333 2211',
    rating: 4.4,
    reviews: 310,
    website: 'http://www.zamalekpowergym.com',
    facebook: 'https://facebook.com/zamalekpowergym',
    openingHours: ['Daily 06:00-23:00'],
    photos: ['gym-1.jpg', 'gym-2.jpg', 'gym-3.jpg'],
    sources: ['google-maps'],
    simulatedProbe: { ok: true, status: 200, timeMs: 1500, isHttps: false, html: '<html><head><title>Zamalek Power Gym</title></head><body><h1>Welcome to Zamalek Power Gym</h1><p>Copyright 2019</p></body></html>' }
  },
  {
    name: 'Alf Lela Hotel',
    category: 'hotel',
    area: 'Luxor',
    country: 'EG',
    address: 'Corniche El Nil, Luxor',
    phone: '+20 95 237 8899',
    whatsapp: '+20 100 222 3344',
    rating: 4.5,
    reviews: 720,
    website: 'https://www.alflelhotel.com',
    instagram: 'https://instagram.com/alflelhotel',
    facebook: 'https://facebook.com/alflelhotel',
    email: 'reservations@alflelhotel.com',
    booking: 'https://www.booking.com/hotel/eg/alf-lela.html',
    openingHours: ['24/7'],
    photos: ['hotel-1.jpg', 'hotel-2.jpg', 'hotel-3.jpg', 'hotel-4.jpg', 'hotel-5.jpg', 'hotel-6.jpg', 'hotel-7.jpg', 'hotel-8.jpg'],
    menus: ['https://www.alflelhotel.com/dining/menu.pdf'],
    sources: ['google-maps', 'website', 'facebook'],
    simulatedProbe: { ok: true, status: 200, timeMs: 700, isHttps: true, html: '<html lang="en"><head><title>Alf Lela Hotel Luxor</title><meta name="description" content="Nile view hotel."><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><h1>Alf Lela Hotel</h1><a href="/reservation">Reserve a room</a><p>&copy; 2024</p></body></html>' }
  },
  {
    name: 'Sheikh Hassan Barbershop',
    category: 'barber',
    area: 'Alexandria',
    country: 'EG',
    address: '14 Safia Zaghloul St, Alexandria',
    phone: '03 486 7755',
    rating: 4.0,
    reviews: 78,
    sources: ['directory']
  },
  {
    name: 'Candy Corner Sweets',
    category: 'dessert',
    area: 'Cairo',
    country: 'EG',
    address: '5 Nasr City, Cairo',
    phone: '02 2402 3344',
    rating: 4.2,
    reviews: 190,
    instagram: 'https://instagram.com/candycornersweets',
    photos: ['candy-1.jpg'],
    sources: ['instagram', 'directory']
  },
  {
    name: 'Oasis Garden Cafe',
    category: 'cafe',
    area: '6th of October',
    country: 'EG',
    address: '88 Wahat Rd, 6th of October City',
    phone: '+20 2 3834 5566',
    whatsapp: '+20 100 888 9911',
    rating: 4.5,
    reviews: 460,
    website: 'https://www.oasisgardencafe.com',
    instagram: 'https://instagram.com/oasisgardencafe',
    facebook: 'https://facebook.com/oasisgardencafe',
    email: 'hello@oasisgardencafe.com',
    booking: 'https://www.oasisgardencafe.com/reservation',
    openingHours: ['Daily 09:00-23:00'],
    photos: ['oasis-1.jpg', 'oasis-2.jpg', 'oasis-3.jpg', 'oasis-4.jpg', 'oasis-5.jpg', 'oasis-6.jpg'],
    menus: ['https://www.oasisgardencafe.com/menu.pdf'],
    sources: ['google-maps', 'website', 'instagram'],
    simulatedProbe: { ok: true, status: 200, timeMs: 410, isHttps: true, html: '<html lang="en"><head><title>Oasis Garden Cafe | Coffee &amp; Food</title><meta name="description" content="Garden cafe in 6th of October."><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><h1>Oasis Garden Cafe</h1><a href="/menu.pdf">Menu</a><a href="/reservation">Book a table</a><p>&copy; 2025</p></body></html>' }
  },
  {
    name: 'Falafel Queen',
    category: 'restaurant',
    area: 'Giza',
    country: 'EG',
    address: '77 Giza St, Giza',
    phone: '+20 2 3571 2233',
    whatsapp: '+20 102 444 5566',
    rating: 4.4,
    reviews: 980,
    website: 'https://www.falafelqueen.com',
    facebook: 'https://facebook.com/falafelqueen',
    openingHours: ['Daily 07:00-22:00'],
    photos: ['falafel-1.jpg', 'falafel-2.jpg', 'falafel-3.jpg', 'falafel-4.jpg'],
    sources: ['google-maps', 'facebook'],
    simulatedProbe: { ok: true, status: 200, timeMs: 820, isHttps: true, html: '<html lang="ar"><head><title>Falafel Queen</title><meta name="description" content="Best falafel in Giza."><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><h1>Falafel Queen</h1><a href="/menu">Menu</a><p>&copy; 2024</p></body></html>' }
  },
  {
    name: 'Blue Wave Beach Hotel',
    category: 'hotel',
    area: 'Hurghada',
    country: 'EG',
    address: 'Sheraton Rd, Hurghada',
    phone: '+20 65 344 7788',
    whatsapp: '+20 100 777 8899',
    rating: 4.0,
    reviews: 640,
    instagram: 'https://instagram.com/bluewavehurghada',
    photos: ['wave-1.jpg', 'wave-2.jpg', 'wave-3.jpg', 'wave-4.jpg'],
    sources: ['instagram', 'directory']
  },
  {
    name: 'Silver Moon Diner',
    category: 'burger',
    area: 'Cairo',
    country: 'EG',
    address: '3 Nasr City, Cairo',
    phone: '+20 2 2262 4455',
    whatsapp: '+20 100 123 9876',
    rating: 4.1,
    reviews: 350,
    website: 'https://www.silvermoondiner.com',
    facebook: 'https://facebook.com/silvermoondiner',
    openingHours: ['Daily 12:00-01:00'],
    photos: ['burger-1.jpg', 'burger-2.jpg', 'burger-3.jpg'],
    sources: ['google-maps'],
    simulatedProbe: { ok: true, status: 200, timeMs: 1900, isHttps: true, html: '<html lang="en"><head><title>Silver Moon Diner</title><meta name="description" content="American diner."><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><p>Welcome</p><p>&copy; 2023</p></body></html>' }
  },
  {
    name: 'Al Nasr Bookstore',
    category: 'other',
    area: 'Cairo',
    country: 'EG',
    address: '21 El Falaki St, Cairo',
    phone: '+20 2 2794 8899',
    rating: 4.2,
    reviews: 120,
    website: 'https://www.alnasrbooks.com',
    email: 'books@alnasrbooks.com',
    openingHours: ['Sat-Thu 09:00-21:00'],
    photos: [],
    sources: ['directory', 'website'],
    simulatedProbe: { ok: true, status: 200, timeMs: 950, isHttps: true, html: '<html lang="en"><head><title>Al Nasr Bookstore</title><meta name="description" content="Bookstore in Cairo."><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><h1>Al Nasr Bookstore</h1><p>&copy; 2025</p></body></html>' }
  }
];
